### ISSUE TITLE
Error in README

### ISSUE THREAD

**Issue by opus-2** [axllent/phpmybackup#2]
Both README.md and the article at https://www.axllent.org/code/phpmybackup/  have the wrong variable names in the usage section:

$db->ignoreList = array('test','unimportant_db');
$db->emptyList = array('largedb.large_table1','largedb.cachetable');

should be:

$db->ignoreDatabases = array('test','unimportant_db');
$db->ignoreTables = array('largedb.large_table1','largedb.cachetable');

...to conform with lines 32 and 38 of the script. Otherwise, they'll be simply not checked and all the data will be backed up, including the databases and tables that were supposed to be ignored.

**Comment by axllent** [comment]
Thank you for reporting this! It's obviously been like this for 4 years or so and nobody has ever reported it.

I really need to update the script at some point soon as it still uses the deprecated php 5.6 `mysql_*` functions which aren't even compatible with php7.
